Set objFso = CreateObject("Scripting.FileSystemObject")
Set objShell = CreateObject("Shell.Application")
Set objFolder = objShell.NameSpace(objFso.GetFolder(".").Path)
Set objFolderItem = objFolder.ParseName("CONSOLA-Powerline.ttf")
objFolderItem.InvokeVerb("Install")
Set objFolderItem = objFolder.ParseName("CONSOLAI-Powerline.ttf")
objFolderItem.InvokeVerb("Install")
Set objFolderItem = objFolder.ParseName("CONSOLAB-Powerline.ttf")
objFolderItem.InvokeVerb("Install")
Set objFolderItem = objFolder.ParseName("CONSOLAZ-Powerline.ttf")
objFolderItem.InvokeVerb("Install")
